### ISSUE TITLE
Unable to install on macOS

### ISSUE THREAD

**Issue by Mowd** [srid/emanote#15] opened 2021-05-23 15:57 UTC
MacOS 11.3.1
Build from master.

I got the error message during the installation:

```
Preprocessing test suite 'example-test' for ap-normalize-0.1.0.0..
Building test suite 'example-test' for ap-normalize-0.1.0.0..
[1 of 1] Compiling Main             ( test/example.hs, dist/build/example-test/example-test-tmp/Main.o, dist/build/example-test/example-test-tmp/Main.dyn_o )
test/example.hs:49:1: traverseNormal === traverseNaive failed expectedly.
test/example.hs:50:1: traverseNormal === traverseAN passed.
test/example.hs:51:1: traverseNormal === traverseTree passed.
inspection testing successful
      expected successes: 2
       expected failures: 1
Linking dist/build/example-test/example-test ...
Preprocessing test suite 'assoc-test' for ap-normalize-0.1.0.0..
Building test suite 'assoc-test' for ap-normalize-0.1.0.0..
[1 of 1] Compiling Main             ( test/assoc.hs, dist/build/assoc-test/assoc-test-tmp/Main.o, dist/build/assoc-test/assoc-test-tmp/Main.dyn_o )

test/assoc.hs:51:151: error:
    • Not in scope: ‘assoc1'Aps’
      Perhaps you meant one of these:
        ‘assoc2'Aps’ (line 51), ‘assoc1'NAME’ (line 51)
    • In the Template Haskell quotation 'assoc1'Aps
   |
51 | TEST_ASSOC_(Aps,Aps f,=/=,Applicative f =>)
   |                                                                                                                                                       ^^^^^^^^^^^

builder for '/nix/store/mgykywgffhw2fc80zh7lv98ygglws07q-ap-normalize-0.1.0.0.drv' failed with exit code 1
cannot build derivation '/nix/store/33wp4ndx99i1p2lm2vs9asyyzkf8nasz-generic-data-0.9.2.0.drv': 1 dependencies couldn't be built
building '/nix/store/kkda0zf90dz306mrc1c2n0lvhscnmrsr-pandoc-link-context-1.0.2.0.drv'...
cannot build derivation '/nix/store/4wwn0n70pi3gkm68wk5lkpn9bys1rxnc-safecopy-0.10.4.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rhsd4hvrhnc95gyd5rf5pbm17smnns34-ixset-typed-0.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nv8701z7dcjr9ibk4c9rf2nlhalm7b3s-emanote-0.1.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/nv8701z7dcjr9ibk4c9rf2nlhalm7b3s-emanote-0.1.0.0.drv' failed
```

**Comment by srid** [comment] 2021-05-23 21:21
@Mowd What command are you using to install it? `nix-env -if ./default.nix`? I would expect it not to compile so many Haskell packages. FWIW, I use [flakes](https://nixos.wiki/wiki/Flakes#Installing_flakes) - but I'm not entirely sure if that's the reason for what you are seeing. It looks like in your case the pinned nixpkgs is not being used.

**Comment by Mowd** [comment] 2021-05-24 03:44
Yes, I use this command: `nix-env -if ./default.nix`.
I'm not familiar with nix, I just use it yesterday by install neuron.
Is there anything I can provide to help you to fix this issue?

**Comment by srid** [comment] 2021-05-24 03:47
@Mowd Could you try this meanwhile?

- Enable Flakes, following the "Non-NixOS" instructions here: https://nixos.wiki/wiki/Flakes#Non-NixOS
- Run `nix run github:srid/emanote -- -C /path/to/notes`

Let me know if that works.

**Comment by Mowd** [comment] 2021-05-24 03:55
The 3rd step gave this error message
```
# sh <(curl -L https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200804_ed52cf6/install)
....
/var/folders/p_/0jznf6lj6wq95lqkn9nf4qq00000gv/T/nix-binary-tarball-unpack.XXXXXXXXXX.GNW8gdtP/unpack/nix-3.0pre20200804_ed52cf6-x86_64-darwin/install: macOS 11.3.1 is not supported, upgrade to 10.12.6 or higher
```

And both  `nix run github:srid/emanote -- -C /path/to/notes` or `nix-env -if ./default.nix` return the same error now.
```
Preprocessing library for recursion-schemes-5.2.2.1..
Building library for recursion-schemes-5.2.2.1..
[1 of 4] Compiling Data.Functor.Base ( src/Data/Functor/Base.hs, dist/build/Data/Functor/Base.o, dist/build/Data/Functor/Base.dyn_o )
[2 of 4] Compiling Data.Functor.Foldable ( src/Data/Functor/Foldable.hs, dist/build/Data/Functor/Foldable.o, dist/build/Data/Functor/Foldable.dyn_o )
[3 of 4] Compiling Data.Functor.Foldable.TH ( src/Data/Functor/Foldable/TH.hs, dist/build/Data/Functor/Foldable/TH.o, dist/build/Data/Functor/Foldable/TH.dyn_o )
[4 of 4] Compiling Paths_recursion_schemes ( dist/build/autogen/Paths_recursion_schemes.hs, dist/build/Paths_recursion_schemes.o, dist/build/Paths_recursion_schemes.dyn_o )
[1 of 4] Compiling Data.Functor.Base ( src/Data/Functor/Base.hs, dist/build/Data/Functor/Base.p_o )
impure path `/private/tmp/nix-build-recursion-schemes-5.2.2.1.drv-0/ghc60168_0/ghc_32.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)
[3 of 4] Compiling Data.Functor.Foldable.TH ( src/Data/Functor/Foldable/TH.hs, dist/build/Data/Functor/Foldable/TH.p_o )
impure path `/private/tmp/nix-build-recursion-schemes-5.2.2.1.drv-0/ghc60168_0/ghc_24.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)
[4 of 4] Compiling Paths_recursion_schemes ( dist/build/autogen/Paths_recursion_schemes.hs, dist/build/Paths_recursion_schemes.p_o )
impure path `/private/tmp/nix-build-recursion-schemes-5.2.2.1.drv-0/ghc60168_0/ghc_16.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)

error: builder for '/nix/store/1b0a4k7s5h6xma046hmiyf1fy0yj7yrb-recursion-schemes-5.2.2.1.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/rh7iqhkgr9h1k59dzxf20h0ll7c9yz62-aeson-extra-0.5.drv' failed to build
building '/nix/store/mgykywgffhw2fc80zh7lv98ygglws07q-ap-normalize-0.1.0.0.drv'...
error: 1 dependencies of derivation '/nix/store/nv8701z7dcjr9ibk4c9rf2nlhalm7b3s-emanote-0.1.0.0.drv' failed to build
```

**Comment by srid** [comment] 2021-05-24 04:03
I think you can ignore the 3rd step (that's only for fresh install, IIUC).

So, `nix run github:srid/emanote -- -C /path/to/notes` is error'ing out too? Hmm...

Let me try to build it on macOS via CI and see what happens ...

(By the way, there is a docker image, but hot reload doesn't work on it, given Docker's limitation)

**Comment by Mowd** [comment] 2021-05-24 04:06
Full command here:

```
# nix run github:srid/emanote -- -C .

error: builder for '/nix/store/1b0a4k7s5h6xma046hmiyf1fy0yj7yrb-recursion-schemes-5.2.2.1.drv' failed with exit code 1;
       last 10 log lines:
       > impure path `/private/tmp/nix-build-recursion-schemes-5.2.2.1.drv-0/ghc61185_0/ghc_24.filelist' used in link
       >
       > <no location info>: error:
       >     `ld' failed in phase `Merge objects'. (Exit code: 1)
       > [4 of 4] Compiling Paths_recursion_schemes ( dist/build/autogen/Paths_recursion_schemes.hs, dist/build/Paths_recursion_schemes.p_o )
       > impure path `/private/tmp/nix-build-recursion-schemes-5.2.2.1.drv-0/ghc61185_0/ghc_16.filelist' used in link
       >
       > <no location info>: error:
       >     `ld' failed in phase `Merge objects'. (Exit code: 1)
       > 
       For full logs, run 'nix log /nix/store/1b0a4k7s5h6xma046hmiyf1fy0yj7yrb-recursion-schemes-5.2.2.1.drv'.
error: 1 dependencies of derivation '/nix/store/rh7iqhkgr9h1k59dzxf20h0ll7c9yz62-aeson-extra-0.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7xb1pq6v43ylixkc3d6pmbsdpg7chiw6-emanote-0.1.0.0.drv' failed to build
```

**Comment by srid** [comment] 2021-05-24 04:14
Just pushed a nixpkgs update to `master` branch of emanote; try again.

(Meanwhile, I'm building on my mac using the previous nixpkgs, to try to reproduce your error)

**Comment by srid** [comment] 2021-05-24 04:23
It failed on my mac too :-(

<img width="1134" alt="gg" src="https://user-images.githubusercontent.com/3998/119295956-10b4de00-bc26-11eb-9b3b-a67989449e4d.png">

I think disabling tests for `ap-normalize` might make it work ....

**Comment by srid** [comment] 2021-05-24 04:29
You can try this patch, and then run `nix run . -- -C ~/mynotes` in the patched repo ... but then be warned that it will compile a lot of Haskell packages (instead of pulling them from cache).

```diff
diff --git a/flake.nix b/flake.nix
index 91fc00b..af5a90a 100644
--- a/flake.nix
+++ b/flake.nix
@@ -37,6 +37,7 @@
               ema = disableCabalFlag inputs.ema.defaultPackage.${system} "with-examples";
               pandoc-link-context = self.callCabal2nix "pandoc-link-context" inputs.pandoc-link-context { };
               # lvar = self.callCabal2nix "lvar" inputs.ema.inputs.lvar { }; # Until lvar gets into nixpkgs
+              ap-normalize = dontCheck (super.ap-normalize);
             };
             modifier = drv:
               pkgs.haskell.lib.addBuildTools drv (with pkgs.haskellPackages;
```

A proper fix will have to be done in https://github.com/NixOS/nixpkgs/ as this package is evidently broken on macOS.

**Comment by srid** [comment] 2021-05-24 04:32
Okay it finished compiling -- took like 5 minutes on a 2014 MBP -- and runs! @Mowd let me know if that above fixes it for you.

**Comment by srid** [comment] 2021-05-24 04:37
https://github.com/NixOS/nixpkgs/pull/124224

**Comment by Mowd** [comment] 2021-05-24 05:03
Still unable to success:
With the latest code from master:

```
# nix run . -- -C ../mynote
.....

[12 of 13] Compiling Ema.App          ( src/Ema/App.hs, dist/build/Ema/App.o, dist/build/Ema/App.dyn_o )
[13 of 13] Compiling Ema              ( src/Ema.hs, dist/build/Ema.o, dist/build/Ema.dyn_o )
[ 1 of 13] Compiling Ema.Asset        ( src/Ema/Asset.hs, dist/build/Ema/Asset.p_o )
impure path `/private/tmp/nix-build-ema-0.2.0.0.drv-0/ghc81651_0/ghc_32.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)
[ 2 of 13] Compiling Ema.CLI          ( src/Ema/CLI.hs, dist/build/Ema/CLI.p_o )
impure path `/private/tmp/nix-build-ema-0.2.0.0.drv-0/ghc81651_0/ghc_31.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)
[ 3 of 13] Compiling Ema.Class        ( src/Ema/Class.hs, dist/build/Ema/Class.p_o )
impure path `/private/tmp/nix-build-ema-0.2.0.0.drv-0/ghc81651_0/ghc_19.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)
[ 5 of 13] Compiling Ema.Helper.FileSystem ( src/Ema/Helper/FileSystem.hs, dist/build/Ema/Helper/FileSystem.p_o )
impure path `/private/tmp/nix-build-ema-0.2.0.0.drv-0/ghc81651_0/ghc_48.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)
[ 6 of 13] Compiling Ema.Helper.Markdown ( src/Ema/Helper/Markdown.hs, dist/build/Ema/Helper/Markdown.p_o )
impure path `/private/tmp/nix-build-ema-0.2.0.0.drv-0/ghc81651_0/ghc_56.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)
[ 7 of 13] Compiling Ema.Helper.PathTree ( src/Ema/Helper/PathTree.hs, dist/build/Ema/Helper/PathTree.p_o )
impure path `/private/tmp/nix-build-ema-0.2.0.0.drv-0/ghc81651_0/ghc_27.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)
[ 9 of 13] Compiling Ema.Route.Slug   ( src/Ema/Route/Slug.hs, dist/build/Ema/Route/Slug.p_o )
impure path `/private/tmp/nix-build-ema-0.2.0.0.drv-0/ghc81651_0/ghc_47.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)
```

**Comment by srid** [comment] 2021-05-24 16:13
At least it got to building Ema itself.

I don't know what the problem here is, sorry. Looks like your macOS linker is tripping up. For some reason, it worked on mine. https://matrix.to/#/#haskell:nixos.org might be able to help.

**Comment by srid** [comment] 2021-05-24 16:51
@Mowd If you don't care about hot reload (because Docker doesn't seem to support inotify well) and have Docker installed, then you can try:

```
docker run -v $PWD:/data sridca/emanote emanote gen /data/output
```

Or, something like this to run the live server (again, hot reload may not work):

```
docker run -p 8000 -v $PWD:/data sridca/emanote emanote 
```

I imagine we might have a solution to the Nix issue by the time emanote gets released officially.

(ema.srid.ca is built using this image: https://github.com/srid/ema/blob/master/.github/workflows/publish.yaml )

**Comment by Mowd** [comment] 2021-05-24 17:23
I removed nix completely and start from scratch, it works now.
1. Follow the instruction of [macOS Installation](https://nixos.org/manual/nix/stable/#sect-macos-installation)
2. Modify [flake.nix](https://github.com/srid/emanote/issues/15#issuecomment-846724060)
3. Run `nix-env -if ./default.nix`
4. Finally you will get a worked emanote.

**Comment by srid** [comment] 2021-05-24 17:28
@Mowd Great to hear! Do you remember what was the cause for the previous Nix install to be corrupt? Was Nix installed *differently* that time (if so how)?

**Comment by Mowd** [comment] 2021-05-25 01:10
This time I didn't install nixUnstable. Just add `experimental-features = nix-command flakes` in `~/.config/nix/nix.conf`
I think it's the problem because new error message appears after install nixUnstable.

**Comment by srid** [comment] 2021-05-25 15:33
> You can try this patch, and then run `nix run . -- -C ~/mynotes` in the patched repo ... but then be warned that it will compile a lot of Haskell packages (instead of pulling them from cache).
> 
> ```diff
> diff --git a/flake.nix b/flake.nix
> index 91fc00b..af5a90a 100644
> --- a/flake.nix
> +++ b/flake.nix
> @@ -37,6 +37,7 @@
>                ema = disableCabalFlag inputs.ema.defaultPackage.${system} "with-examples";
>                pandoc-link-context = self.callCabal2nix "pandoc-link-context" inputs.pandoc-link-context { };
>                # lvar = self.callCabal2nix "lvar" inputs.ema.inputs.lvar { }; # Until lvar gets into nixpkgs
> +              ap-normalize = dontCheck (super.ap-normalize);
>              };
>              modifier = drv:
>                pkgs.haskell.lib.addBuildTools drv (with pkgs.haskellPackages;
> ```
> 
> A proper fix will have to be done in https://github.com/NixOS/nixpkgs/ as this package is evidently broken on macOS.

Just fixed in nixpkgs master: https://github.com/NixOS/nixpkgs/commit/d1f97a0dfb208ec20f982860c5740cd08dd35ef2

Should take about a week before it is made avaialble in the cache, and then we can update emanote and close this issue.

**Comment by srid** [comment] 2021-06-09 23:40
Confirmed to be fixed in latest `master`.

**Closed as completed by srid** 2021-06-09 23:40 UTC
