### ISSUE TITLE
Unicode Character Support

### ISSUE THREAD

**Issue by SpyrosMourelatos** [srid/emanote#248] opened 2022-02-09 12:23 UTC
I have a knowledge base in Greek language that I am trying to use with emanote.
It kind of works but the greek characters at some places are corrupted
![20220209141238](https://user-images.githubusercontent.com/26333139/153200124-b8f7a3ae-bbce-4944-a903-e1262a28a647.png)
To Reproduce take my zip and run `emanote run`
 - Browser both firefox and chrome
firefox --version
Mozilla Firefox 96.0.3
chromium --version
Chromium 97.0.4692.99 Manjaro Linux
[testemmanote.zip](https://github.com/srid/emanote/files/8032597/testemmanote.zip)

**Comment by SpyrosMourelatos** [comment] 2022-02-09 12:50
Also by noticing a relevant bug with chinese
![image](https://user-images.githubusercontent.com/26333139/153204476-5c12ca42-378f-4402-98d5-2543a7b67b50.png)

**Comment by SpyrosMourelatos** [comment] 2022-02-09 13:02
And  by the way is fixed with LANG=C.UTF-8

**Comment by haoyun** [comment] 2022-02-09 22:53
Are you using Nix? if so, i think it's related to or a duplicate of https://github.com/srid/emanote/issues/125. And the problems is with Nix environment.

**Comment by SpyrosMourelatos** [comment] 2022-02-10 10:48
@haoyun 
I am not using the os named Nix, I only use the package manager as this is the suggested way to install emanote, is there an alternative?
The os is Manjaro and ubuntu (as I run it on github pages also)
I don't request a fix , probably just adding it to the readme so people would find the fix easier is enough for now

**Comment by srid** [comment] 2022-02-10 22:42
@SpyrosMourelatos The package manager is called Nix; and the OS is called NixOS.

I'm closing this as a duplicate of #125 ... at minimum we should document this workaround.

**Closed as completed by srid** 2022-02-10 22:42 UTC
Labels: bug, unicode
